# Form implementation generated from reading ui file 'ui/SpectrumWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpectrumWidget(object):
    def setupUi(self, SpectrumWidget):
        SpectrumWidget.setObjectName("SpectrumWidget")
        SpectrumWidget.resize(900, 550)
        self.graphWidget = PlotWidget(parent=SpectrumWidget)
        self.graphWidget.setGeometry(QtCore.QRect(110, 10, 771, 521))
        self.graphWidget.setAcceptDrops(True)
        self.graphWidget.setObjectName("graphWidget")
        self.removePlotButton = QtWidgets.QPushButton(parent=SpectrumWidget)
        self.removePlotButton.setGeometry(QtCore.QRect(14, 60, 81, 23))
        self.removePlotButton.setObjectName("removePlotButton")
        self.addPlotButton = QtWidgets.QPushButton(parent=SpectrumWidget)
        self.addPlotButton.setGeometry(QtCore.QRect(14, 20, 81, 23))
        self.addPlotButton.setObjectName("addPlotButton")
        self.colorButton = QtWidgets.QPushButton(parent=SpectrumWidget)
        self.colorButton.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.colorButton.setObjectName("colorButton")
        self.clearPlotButton = QtWidgets.QPushButton(parent=SpectrumWidget)
        self.clearPlotButton.setGeometry(QtCore.QRect(14, 100, 81, 23))
        self.clearPlotButton.setObjectName("clearPlotButton")
        self.listWidget = QtWidgets.QListWidget(parent=SpectrumWidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 140, 91, 131))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(SpectrumWidget)
        QtCore.QMetaObject.connectSlotsByName(SpectrumWidget)

    def retranslateUi(self, SpectrumWidget):
        _translate = QtCore.QCoreApplication.translate
        SpectrumWidget.setWindowTitle(_translate("SpectrumWidget", "Form"))
        self.removePlotButton.setText(_translate("SpectrumWidget", "Remove plot"))
        self.addPlotButton.setText(_translate("SpectrumWidget", "Add plot"))
        self.colorButton.setText(_translate("SpectrumWidget", "Color"))
        self.clearPlotButton.setText(_translate("SpectrumWidget", "Clear all"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpectrumWidget = QtWidgets.QWidget()
    ui = Ui_SpectrumWidget()
    ui.setupUi(SpectrumWidget)
    SpectrumWidget.show()
    sys.exit(app.exec())
