# Form implementation generated from reading ui file 'SweepLoading.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_sweepLoading(object):
    def setupUi(self, sweepLoading):
        sweepLoading.setObjectName("sweepLoading")
        sweepLoading.resize(243, 112)
        self.label = QtWidgets.QLabel(parent=sweepLoading)
        self.label.setGeometry(QtCore.QRect(30, 20, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")


        self.retranslateUi(sweepLoading)
        QtCore.QMetaObject.connectSlotsByName(sweepLoading)

    def retranslateUi(self, sweepLoading):
        _translate = QtCore.QCoreApplication.translate
        sweepLoading.setWindowTitle(_translate("sweepLoading", "Form"))
        self.label.setText(_translate("sweepLoading", "OSA sweeping"))
