# Form implementation generated from reading ui file 'ui/WelcomeWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWidget(object):
    def setupUi(self, WelcomeWidget):
        WelcomeWidget.setObjectName("WelcomeWidget")
        WelcomeWidget.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(16)
        WelcomeWidget.setFont(font)
        self.startLabel = QtWidgets.QLabel(parent=WelcomeWidget)
        self.startLabel.setGeometry(QtCore.QRect(50, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.startLabel.setFont(font)
        self.startLabel.setObjectName("startLabel")
        self.newPiezoButton = QtWidgets.QPushButton(parent=WelcomeWidget)
        self.newPiezoButton.setGeometry(QtCore.QRect(40, 70, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newPiezoButton.setFont(font)
        self.newPiezoButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: lightblue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: blue;\n"
"}")
        self.newPiezoButton.setObjectName("newPiezoButton")
        self.newOSAButton = QtWidgets.QPushButton(parent=WelcomeWidget)
        self.newOSAButton.setGeometry(QtCore.QRect(40, 110, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newOSAButton.setFont(font)
        self.newOSAButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: lightblue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: blue;\n"
"}")
        self.newOSAButton.setObjectName("newOSAButton")
        self.viewSpectrumButton = QtWidgets.QPushButton(parent=WelcomeWidget)
        self.viewSpectrumButton.setGeometry(QtCore.QRect(30, 150, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.viewSpectrumButton.setFont(font)
        self.viewSpectrumButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: lightblue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: blue;\n"
"}")
        self.viewSpectrumButton.setObjectName("viewSpectrumButton")
        self.gainChipButton = QtWidgets.QPushButton(parent=WelcomeWidget)
        self.gainChipButton.setGeometry(QtCore.QRect(40, 190, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gainChipButton.setFont(font)
        self.gainChipButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: lightblue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: blue;\n"
"}")
        self.gainChipButton.setObjectName("gainChipButton")
        self.newSMUButton = QtWidgets.QPushButton(parent=WelcomeWidget)
        self.newSMUButton.setGeometry(QtCore.QRect(40, 230, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newSMUButton.setFont(font)
        self.newSMUButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: lightblue;\n"
"}\n"
"QPushButton:hover {\n"
"    color: blue;\n"
"}")
        self.newSMUButton.setObjectName("newSMUButton")

        self.retranslateUi(WelcomeWidget)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWidget)

    def retranslateUi(self, WelcomeWidget):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWidget.setWindowTitle(_translate("WelcomeWidget", "Form"))
        self.startLabel.setText(_translate("WelcomeWidget", "Start"))
        self.newPiezoButton.setText(_translate("WelcomeWidget", "Piezo Stage Control →"))
        self.newOSAButton.setText(_translate("WelcomeWidget", "Optical Spectrum Analyzer (OSA) →"))
        self.viewSpectrumButton.setText(_translate("WelcomeWidget", "View Spectrum →"))
        self.gainChipButton.setText(_translate("WelcomeWidget", "Gain Chip Control →"))
        self.newSMUButton.setText(_translate("WelcomeWidget", "Source Measurement Unit (SMU) →"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeWidget = QtWidgets.QWidget()
    ui = Ui_WelcomeWidget()
    ui.setupUi(WelcomeWidget)
    WelcomeWidget.show()
    sys.exit(app.exec())
